#DATA:
read_size: 10000 # taille des fenêtres dans le génom dans lequel ce fait le comptage
max_sampling: 100 # nombres de fenetres dans un génome .fna,  # if null, shift_ratio should be specified
shift_ratio: null  # if null, max_sampling should be specified
ksize: 4 # taille des kmers
pattern: # motif à prendre en compte dans le kmer
  - 1
  - 1
  - 1
  - 1
min_family_threshold: 10 # minimum davg_nb_count_wine représentant espèce par famille
max_family_repr: inf # maximum de représentant espèce par famille
test_size: 0.1 # pourcentage du split train/val
random_state: 42 # seed pour xgboost, et le split train/val

#MODEL XGBOOST: params
num_processes: 2
eval_metric: mlogloss
tree_method: hist
device: cpu
booster: gbtree
objective: multi:softprob
num_rounds_boosting: 10
eta: 0.3
max_depth: 10

#PREDICT:
threshold: 0.6 # threshold (float): threshold to consider a taxa as accurate
# "threshold au dela duquel ne pas aller dans l autre branche"
normalisation_func: delta_mean
read_identity_threshold: 0.8