#DATA:
sampling: 100 # nombres de fenetres dans un génome .fna
read_size: 10000 # taille des fenêtres dans le génom
ksize: 4 # taille des kmers
pattern:
  - 1
  - 1
  - 1
  - 1

min_family_threshold: 5
max_family_repr: inf
test_size: 0.2
random_state: 42

#MODEL:
num_processes: 8
eval_metric: mlogloss
tree_method: hist
device: cpu
booster: gbtree
objective: multi:softprob
num_rounds_boosting: 10
eta: 0.3
max_depth: 10

#PREDICT:
threshold: 0.6 # "threshold au dela duquel ne pas aller dans l autre branche"
# threshold (float): threshold to consider a taxa as accurate
normalisation_func: delta_mean
read_identity_threshold: 0.8