#DATA:
read_size: 10000
ksize: 4
pattern:
  - 1
  - 1
  - 1
  - 1
sampling: 100
min_family_threshold: 10
max_family_repr: 50
test_size: 0.1
random_state: 42

#MODEL:
num_processes: 8
eval_metric: mlogloss
tree_method: hist
device: cpu
booster: gbtree
objective: multi:softprob
num_rounds_boosting: 10
eta: 0.3
max_depth: 10

#PREDICT:
threshold: 0.6 # "threshold au dela duquel ne pas aller dans l autre branche"
# threshold (float): threshold to consider a taxa as accurate
normalisation_func: delta_mean
read_identity_threshold: 0.8